# Generated by Django 4.2.23 on 2025-07-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20240129_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age_minimal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='enrolment_discount_perc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='enrolment_discount_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='general_assembly_fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='general_assembly_lump_sum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grace_period_enrolment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grace_period_payment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grace_period_renewal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='insurance_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_installments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='product',
            name='premium_child',
        ),
        migrations.RemoveField(
            model_name='product',
            name='renewal_discount_perc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='renewal_discount_period',
        ),
    ]
