# Generated by Django 4.2.23 on 2025-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_age_minimal_remove_product_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enrolment_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enrolment_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
