# Generated by Django 4.2.23 on 2025-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_membershiptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='membership_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.membershiptype'),
        ),
    ]
