# Generated by Django 4.2.23 on 2025-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_add_card_replacement_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_replacement_fee',
            field=models.DecimalField(db_column='CardReplacementFee', decimal_places=2, default=1, max_digits=18, verbose_name='Card Replacement Fee'),
        ),
    ]
