# Generated by Django 4.2.23 on 2025-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_card_replacement_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chf_id_format',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Format 1'), (2, 'Format 2'), (3, 'Format 3')], db_column='CHFIDFormat', default=1, help_text='CHF ID format (1, 2 or 3)'),
        ),
    ]
