# Generated by Django 4.2.23 on 2025-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_chf_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='is_indigent',
            field=models.BooleanField(db_column='IsIndigent', default=False),
        ),
    ]
