# Generated by Django 4.2.23 on 2025-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_membershiptype_is_indigent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='district',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='region',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='district_id',
            field=models.IntegerField(blank=True, db_column='DistrictID', null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='region_id',
            field=models.IntegerField(db_column='RegionID', null=True),
        ),
    ]
