# Generated by Django 4.2.23 on 2025-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_membershiptype_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverage_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
