# Generated by Django 4.2.23 on 2025-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_coverage_period_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='penalty_price',
            field=models.DecimalField(blank=True, db_column='PenaltyPrice', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spousal_extension_contribution',
            field=models.DecimalField(blank=True, db_column='AdditionalSpouseContribution', decimal_places=2, max_digits=18, null=True),
        ),
    ]
