# Generated by Django 4.2.23 on 2025-09-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_penalty_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spousal_extension_contribution',
            new_name='additional_spouse_contribution',
        ),
    ]
