# Generated by Django 4.2.23 on 2025-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_rename_spousal_extension_contribution_product_additional_spouse_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lump_sum',
            field=models.DecimalField(blank=True, db_column='LumpSum', decimal_places=2, max_digits=18, null=True),
        ),
    ]
