# Generated by Django 4.2.23 on 2025-09-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_lump_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, db_column='ParentProdID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='product.product'),
        ),
    ]
