# Generated by Django 4.2.23 on 2025-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='penalityFormula',
            field=models.CharField(blank=True, db_column='PenalityFormula', max_length=100, null=True),
        ),
    ]
