# Generated by Django 4.2.24 on 2025-10-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_penalityformula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='penalityFormula',
            new_name='penality_formula',
        ),
    ]
