# Generated by Django 4.2.26 on 2025-12-24 09:30

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_laboratoryservice_alter_service_care_type_and_more'),
        ('product', '0025_rename_penalityformula_product_penality_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLaboratoryService',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ProdLabServiceID', primary_key=True, serialize=False)),
                ('price_origin', models.CharField(choices=[('P', 'Schema Price'), ('O', 'Providers Own Price'), ('R', 'Relative Price')], db_column='PriceOrigin', max_length=1)),
                ('limit_adult', models.DecimalField(blank=True, db_column='LimitAdult', decimal_places=2, max_digits=18, null=True)),
                ('limit_child', models.DecimalField(blank=True, db_column='LimitChild', decimal_places=2, max_digits=18, null=True)),
                ('waiting_period_adult', models.IntegerField(blank=True, db_column='WaitingPeriodAdult', null=True)),
                ('waiting_period_child', models.IntegerField(blank=True, db_column='WaitingPeriodChild', null=True)),
                ('limit_no_adult', models.IntegerField(blank=True, db_column='LimitNoAdult', null=True)),
                ('limit_no_child', models.IntegerField(blank=True, db_column='LimitNoChild', null=True)),
                ('limitation_type', models.CharField(choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationType', max_length=1)),
                ('limitation_type_r', models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationTypeR', max_length=1, null=True)),
                ('limitation_type_e', models.CharField(blank=True, choices=[('F', 'Fixed'), ('C', 'Co-insurance')], db_column='LimitationTypeE', max_length=1, null=True)),
                ('limit_adult_r', models.DecimalField(blank=True, db_column='LimitAdultR', decimal_places=2, max_digits=18, null=True)),
                ('limit_adult_e', models.DecimalField(blank=True, db_column='LimitAdultE', decimal_places=2, max_digits=18, null=True)),
                ('limit_child_r', models.DecimalField(blank=True, db_column='LimitChildR', decimal_places=2, max_digits=18, null=True)),
                ('limit_child_e', models.DecimalField(blank=True, db_column='LimitChildE', decimal_places=2, max_digits=18, null=True)),
                ('ceiling_exclusion_adult', models.CharField(blank=True, db_column='CeilingExclusionAdult', max_length=1, null=True)),
                ('ceiling_exclusion_child', models.CharField(blank=True, db_column='CeilingExclusionChild', max_length=1, null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('lab_service', models.ForeignKey(db_column='LabServiceID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_services', to='medical.laboratoryservice')),
                ('product', models.ForeignKey(db_column='ProdID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_services', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Laboratory Service',
                'verbose_name_plural': 'Product Laboratory Services',
                'db_table': 'tblProductLabServices',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model, product.models.ProductItemOrService),
        ),
    ]
